name: Build and Deploy

on:
  push:
    branches:
      - main  # Or specify your main branch here
env:
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN  }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'  # Or specify your desired .NET version here

    - name: Build and Test
      run: |
        dotnet build ./App/App.csproj
        dotnet test ./App/App.csproj

    - name: Save DLL as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: '**/*.dll'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Login to Docker Hub
      run: docker login -username "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_PASSWORD"
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN  }}

    - name: Build Docker image
      run: docker build -t ayeondocker/app:tagname .

    - name: Push Docker image to Docker Hub
      run: docker push ayeondocker/app:tagname
