name: Build and Deploy

on:
  push:
    branches:
      - main  # Or specify your main branch here
# env: dev
#   # DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN  }}
#   # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  
      

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'  # Or specify your desired .NET version here

    - name: Build and Test
      run: |
        dotnet build ./App/App.csproj
        dotnet test ./App/App.csproj

    - name: Save DLL as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: '**/*.dll'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    # - name: Login to Docker Hub
    #   run: echo "$DOCKER_REGISTRY_PASSWORD" | docker login -username "$DOCKER_REGISTRY_USERNAME" --password-stdin 
  #     uses: docker/login-action@v3
  #     with:
  #       username: '${{ secrets.DOCKER_USERNAME }}'
  #       password: '${{ secrets.DOCKERHUB_TOKEN  }}'
                
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: '${{ secrets.DOCKER_USERNAME }}'
        # Password or personal access token used to log against the Docker registry
        password: '${{ secrets.DOCKERHUB_TOKEN  }}'
        # # Specifies whether the given registry is ECR (auto, true or false)
      # ecr: # optional, default is auto
      # # Log out from the Docker registry at the end of a job
      # logout: # optional, default is true
          

    - name: Build Docker image
      run: docker build -t ayeondocker/app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ayeondocker/app:latest
