name: Build and Deploy

on:
  push:
    branches:
      - main  # Or specify your main branch here

      

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'  # Or specify your desired .NET version here

    - name: Build and Test
      run: |
        dotnet build ./App/App.csproj
        dotnet test ./App/App.csproj
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    
    - name: Confirm git commit SHA output
      run: echo ${{ env.COMMIT_SHORT_SHA }}
    

    - name: Save DLL as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: App-${{ env.COMMIT_SHORT_SHA }}
        path: '**/*.dll'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

   
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: '${{ secrets.DOCKER_USERNAME }}'
        # Password or personal access token used to log against the Docker registry
        password: '${{ secrets.DOCKERHUB_TOKEN  }}'
        # # Specifies whether the given registry is ECR (auto, true or false)
      # ecr: # optional, default is auto
      # # Log out from the Docker registry at the end of a job
      # logout: # optional, default is true
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
    
    - name: Confirm git commit SHA output
      run: echo ${{ env.COMMIT_SHORT_SHA }}  
          

    - name: Build Docker image
      run: docker build -t ayeondocker/app:${{ env.COMMIT_SHORT_SHA }} .

    - name: Push Docker image to Docker Hub
      run: docker push ayeondocker/app:${{ env.COMMIT_SHORT_SHA }}
